CREATE DATABASE HelpList;
use HelpList;

CREATE TABLE Help(
    idx INT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    age INT(5) NOT NULL,
    gender VARCHAR(1) NOT NULL,
    title TEXT,
    content TEXT,
    today DATETIME DEFAULT CURRENT_TIMESTAMP,
    hit INT(11) DEFAULT 0
    
) AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;